# Woodpecker CI Pipeline Configuration for git-updater
# Documentation: https://woodpecker-ci.org/

variables:
  - &golang_image 'golang:1.25.10-alpine'
  - &buildkit_image 'moby/buildkit:v0.31.0'

steps:
  # Step 1: Format check and Static Analysis (Go Vet)
  - name: lint-and-vet
    image: *golang_image
    commands:
      - go fmt ./...
      - go vet ./...
    when:
      event: [push, pull_request, manual]
      branch: dev
      
  # Step 2: Build and Push Docker image using BuildKit
  - name: build-and-push-nightly
    image: *buildkit_image
    commands:
      - buildctl build \
          --addr tcp://buildkit.buildkit.svc.cluster.local:2395 \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --output type=image,name=registry.xheize.cc/git-updater:nightly-${CI_COMMIT_SHA:0:8},push=true \
          --output type=image,name=registry.xheize.cc/git-updater:nightly,push=true
    when:
      event: [push, cron, manual]
      branch: [main]
      
  # Step 3: Build and Push Docker image using BuildKit
  - name: build-and-push-latest
    image: *buildkit_image
    commands:
      - buildctl build \
          --addr tcp://buildkit.buildkit.svc.cluster.local:2395 \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --output type=image,name=registry.xheize.cc/git-updater:${CI_COMMIT_TAG},push=true \
          --output type=image,name=registry.xheize.cc/git-updater:latest,push=true
    when:
      event: [tag]
      branch: [main]
